"""Shared constants for engine, card definitions, and actions."""

INKS = {"amber", "amethyst", "emerald", "ruby", "sapphire", "steel"}

CARD_CHARACTER = "character"
CARD_ACTION = "action"
CARD_ITEM = "item"
CARD_LOCATION = "location"
CARD_TYPES = {CARD_CHARACTER, CARD_ACTION, CARD_ITEM, CARD_LOCATION}

ZONE_DECK = "deck"
ZONE_HAND = "hand"
ZONE_PLAY = "play"
ZONE_DISCARD = "discard"
ZONE_INKWELL = "inkwell"

ACTION_END_TURN = "END_TURN"
ACTION_INK_CARD = "INK_CARD"
ACTION_PLAY_CARD = "PLAY_CARD"
ACTION_QUEST = "QUEST"
ACTION_CHALLENGE = "CHALLENGE"
ACTION_USE_ABILITY = "USE_ABILITY"
ACTION_MOVE_TO_LOCATION = "MOVE_TO_LOCATION"
ACTION_KEEP_HAND = "KEEP_HAND"
ACTION_MULLIGAN = "MULLIGAN"
ACTION_CONCEDE = "CONCEDE"
ACTION_RESOLVE_BAG = "RESOLVE_BAG"

PHASE_MULLIGAN = "MULLIGAN"
PHASE_MAIN = "MAIN"
PHASE_GAME_OVER = "GAME_OVER"

KEYWORD_EVASIVE = "EVASIVE"
KEYWORD_RUSH = "RUSH"
KEYWORD_BODYGUARD = "BODYGUARD"
KEYWORD_RECKLESS = "RECKLESS"
KEYWORD_WARD = "WARD"
KEYWORD_RESIST = "RESIST"

# Canonical trigger event names (Lorcanito-aligned)
TRIGGER_EVENT_PLAY = "play"
TRIGGER_EVENT_QUEST = "quest"
TRIGGER_EVENT_CHALLENGE = "challenge"
TRIGGER_EVENT_BANISH = "banish"
TRIGGER_EVENT_START_TURN = "start-turn"
TRIGGER_EVENT_END_TURN = "end-turn"
TRIGGER_EVENT_INK = "ink"
TRIGGER_EVENT_CHALLENGED = "challenged"
TRIGGER_EVENT_DAMAGE = "damage"
TRIGGER_EVENT_EXERT = "exert"
TRIGGER_EVENT_READY = "ready"
TRIGGER_EVENT_SING = "sing"
TRIGGER_EVENT_MOVE = "move"
TRIGGER_EVENT_LEAVE_PLAY = "leave-play"

# Event constants for trigger pipeline
EVENT_TRIGGER_QUEUED = "TRIGGER_QUEUED"
EVENT_TRIGGER_RESOLVED = "TRIGGER_RESOLVED"
EVENT_TRIGGER_DECLINED = "TRIGGER_DECLINED"
EVENT_TRIGGER_SKIPPED = "TRIGGER_SKIPPED"
EVENT_TRIGGER_EVENT_BUFFERED = "TRIGGER_EVENT_BUFFERED"

# Legacy event mappings (kept for compatibility)
EVENT_TURN_START = "TURN_START"
EVENT_CARD_PLAYED = "CARD_PLAYED"
EVENT_QUESTED = "QUESTED"
EVENT_CHALLENGE_STARTED = "CHALLENGE_STARTED"
EVENT_CHARACTER_BANISHED = "CHARACTER_BANISHED"
EVENT_TURN_END = "TURN_END"
EVENT_KEPT_HAND = "KEPT_HAND"
EVENT_MULLIGANED = "MULLIGANED"
EVENT_CONCEDED = "CONCEDED"
EVENT_MOVED_TO_LOCATION = "MOVED_TO_LOCATION"
EVENT_LOCATION_LORE_GAINED = "LOCATION_LORE_GAINED"
EVENT_INKED = "INKED"

FORMAT_CORE_CONSTRUCTED = "core_constructed"
