"""Shared constants for engine, card definitions, and actions."""

INKS = {"amber", "amethyst", "emerald", "ruby", "sapphire", "steel"}

CARD_CHARACTER = "character"
CARD_ACTION = "action"
CARD_ITEM = "item"
CARD_LOCATION = "location"
CARD_TYPES = {CARD_CHARACTER, CARD_ACTION, CARD_ITEM, CARD_LOCATION}

ZONE_DECK = "deck"
ZONE_HAND = "hand"
ZONE_PLAY = "play"
ZONE_DISCARD = "discard"
ZONE_INKWELL = "inkwell"
ZONE_LIMBO = "limbo"
# B12: Shift stack zone - cards placed under a shifted character
ZONE_UNDER = "under"

ACTION_END_TURN = "END_TURN"
ACTION_INK_CARD = "INK_CARD"
ACTION_PLAY_CARD = "PLAY_CARD"
ACTION_QUEST = "QUEST"
ACTION_CHALLENGE = "CHALLENGE"
ACTION_USE_ABILITY = "USE_ABILITY"
ACTION_MOVE_TO_LOCATION = "MOVE_TO_LOCATION"
ACTION_KEEP_HAND = "KEEP_HAND"
ACTION_MULLIGAN = "MULLIGAN"
ACTION_CONCEDE = "CONCEDE"
ACTION_RESOLVE_BAG = "RESOLVE_BAG"
ACTION_RESOLVE_PENDING_EFFECT = "RESOLVE_PENDING_EFFECT"
# B10: Alternative play modes (Songs, Shift)
ACTION_SING_SONG = "SING_SONG"
ACTION_PLAY_SHIFTED = "PLAY_SHIFTED"

PHASE_MULLIGAN = "MULLIGAN"
PHASE_MAIN = "MAIN"
PHASE_GAME_OVER = "GAME_OVER"

KEYWORD_EVASIVE = "EVASIVE"
KEYWORD_RUSH = "RUSH"
KEYWORD_BODYGUARD = "BODYGUARD"
KEYWORD_RECKLESS = "RECKLESS"
KEYWORD_WARD = "WARD"
KEYWORD_RESIST = "RESIST"

# Canonical trigger event names (Lorcanito-aligned)
TRIGGER_EVENT_PLAY = "play"
TRIGGER_EVENT_QUEST = "quest"
TRIGGER_EVENT_CHALLENGE = "challenge"
TRIGGER_EVENT_BANISH = "banish"
TRIGGER_EVENT_BANISH_IN_CHALLENGE = "banish-in-challenge"
TRIGGER_EVENT_START_TURN = "start-turn"
TRIGGER_EVENT_END_TURN = "end-turn"
TRIGGER_EVENT_INK = "ink"
TRIGGER_EVENT_CHALLENGED = "challenged"
TRIGGER_EVENT_DAMAGE = "damage"
TRIGGER_EVENT_EXERT = "exert"
TRIGGER_EVENT_READY = "ready"
TRIGGER_EVENT_SING = "sing"
TRIGGER_EVENT_MOVE = "move"
TRIGGER_EVENT_LEAVE_PLAY = "leave-play"
TRIGGER_EVENT_DISCARD = "discard"
TRIGGER_EVENT_RETURN_TO_HAND = "return-to-hand"
TRIGGER_EVENT_DRAW = "draw"
TRIGGER_EVENT_GAIN_LORE = "gain-lore"
TRIGGER_EVENT_LOSE_LORE = "lose-lore"
TRIGGER_EVENT_SUPPORT = "support"
TRIGGER_EVENT_DAMAGE_DEALT = "deal-damage"
TRIGGER_EVENT_BOOST = "boost"
TRIGGER_EVENT_BE_CHOSEN = "be-chosen"
TRIGGER_EVENT_PUT_CARD_UNDER = "put-card-under"

# Event constants for trigger pipeline
EVENT_TRIGGER_QUEUED = "TRIGGER_QUEUED"
EVENT_TRIGGER_RESOLVED = "TRIGGER_RESOLVED"
EVENT_TRIGGER_DECLINED = "TRIGGER_DECLINED"
EVENT_TRIGGER_SKIPPED = "TRIGGER_SKIPPED"
EVENT_TRIGGER_EVENT_BUFFERED = "TRIGGER_EVENT_BUFFERED"

# Gameplay event constants (aligned with Lorcanito domain-events)
EVENT_TURN_START = "TURN_START"
EVENT_TURN_END = "TURN_END"
EVENT_CARD_PLAYED = "CARD_PLAYED"
EVENT_INKED = "INKED"
EVENT_QUESTED = "QUESTED"
EVENT_CHALLENGE_STARTED = "CHALLENGE_STARTED"
EVENT_CHALLENGED = "CHALLENGED"
EVENT_DAMAGE_DEALT = "DAMAGE_DEALT"
EVENT_CHARACTER_BANISHED = "CHARACTER_BANISHED"
EVENT_MOVED_TO_LOCATION = "MOVED_TO_LOCATION"
EVENT_LOCATION_LORE_GAINED = "LOCATION_LORE_GAINED"
EVENT_LORE_GAINED = "LORE_GAINED"
EVENT_LORE_LOST = "LORE_LOST"
EVENT_CARD_DISCARDED = "CARD_DISCARDED"
EVENT_CARD_RETURNED_TO_HAND = "CARD_RETURNED_TO_HAND"
EVENT_CARD_READIED = "CARD_READIED"
EVENT_CARD_EXERTED = "CARD_EXERTED"
EVENT_CARD_DRAWN = "CARD_DRAWN"
EVENT_KEPT_HAND = "KEPT_HAND"
EVENT_MULLIGANED = "MULLIGANED"
EVENT_CONCEDED = "CONCEDED"
EVENT_SUPPORT = "SUPPORT"
EVENT_BANISH_IN_CHALLENGE = "BANISH_IN_CHALLENGE"
EVENT_PUT_CARD_UNDER = "PUT_CARD_UNDER"
EVENT_BE_CHOSEN = "BE_CHOSEN"

# All gameplay events for iteration
ALL_GAMEPLAY_EVENTS = frozenset({
    EVENT_TURN_START,
    EVENT_TURN_END,
    EVENT_CARD_PLAYED,
    EVENT_INKED,
    EVENT_QUESTED,
    EVENT_CHALLENGE_STARTED,
    EVENT_CHALLENGED,
    EVENT_DAMAGE_DEALT,
    EVENT_CHARACTER_BANISHED,
    EVENT_MOVED_TO_LOCATION,
    EVENT_LOCATION_LORE_GAINED,
    EVENT_LORE_GAINED,
    EVENT_LORE_LOST,
    EVENT_CARD_DISCARDED,
    EVENT_CARD_RETURNED_TO_HAND,
    EVENT_CARD_READIED,
    EVENT_CARD_EXERTED,
    EVENT_CARD_DRAWN,
    EVENT_SUPPORT,
    EVENT_BANISH_IN_CHALLENGE,
    EVENT_PUT_CARD_UNDER,
})

# Legacy event mappings — canonical names used by trigger projection and matching.
# Maps LorcanaChamp GameEvent.event_type strings to Lorcanito-aligned trigger event names.
LEGACY_EVENT_MAP = {
    # Turn lifecycle
    "TURN_START": TRIGGER_EVENT_START_TURN,
    "TURN_END": TRIGGER_EVENT_END_TURN,
    # Play / ink
    "CARD_PLAYED": TRIGGER_EVENT_PLAY,
    "INKED": TRIGGER_EVENT_INK,
    # Quest / challenge
    "QUESTED": TRIGGER_EVENT_QUEST,
    "CHALLENGE_STARTED": TRIGGER_EVENT_CHALLENGE,
    "CHALLENGED": TRIGGER_EVENT_CHALLENGED,
    # Damage / banish
    "DAMAGE_DEALT": TRIGGER_EVENT_DAMAGE_DEALT,
    "CHARACTER_BANISHED": TRIGGER_EVENT_BANISH,
    "BANISH_IN_CHALLENGE": TRIGGER_EVENT_BANISH_IN_CHALLENGE,
    # Deck / hand / discard / return / ready / exert
    "CARD_DRAWN": TRIGGER_EVENT_DRAW,
    "CARD_DISCARDED": TRIGGER_EVENT_DISCARD,
    "CARD_RETURNED_TO_HAND": TRIGGER_EVENT_RETURN_TO_HAND,
    "CARD_READIED": TRIGGER_EVENT_READY,
    "CARD_EXERTED": TRIGGER_EVENT_EXERT,
    # Movement / lore / support
    "MOVED_TO_LOCATION": TRIGGER_EVENT_MOVE,
    "LOCATION_LORE_GAINED": TRIGGER_EVENT_GAIN_LORE,
    "LORE_GAINED": TRIGGER_EVENT_GAIN_LORE,
    "LORE_LOST": TRIGGER_EVENT_LOSE_LORE,
    "SUPPORT": TRIGGER_EVENT_SUPPORT,
    "PUT_CARD_UNDER": TRIGGER_EVENT_PUT_CARD_UNDER,
    "BE_CHOSEN": TRIGGER_EVENT_BE_CHOSEN,
}

FORMAT_CORE_CONSTRUCTED = "core_constructed"
